In [1]:

# import packages

import warnings
warnings.simplefilter('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
# pickle is used to save the model created by us

In [3]:
df = pd.read_csv("../input/salary-prediction/hiring.csv")
df.head()

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [4]:
df.isna().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [5]:
# experience
df['experience'].fillna(0,inplace = True)
df.isna().sum()

experience         0
test_score         1
interview_score    0
salary             0
dtype: int64

In [6]:
df['test_score'].fillna(df['test_score'].mean(),inplace = True)
df.isna().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

In [7]:
df.head()

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [8]:
X = df.iloc[:,:-1]  #all the columns except -1th column as dependent variables
X.head()

experience  test_score  interview_score
0          0         8.0                9
1          0         8.0                6
2       five         6.0                7
3        two        10.0               10
4      seven         9.0                6

In [9]:
X.shape

(8, 3)

In [10]:
X.experience

0         0
1         0
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [11]:
# convert text into intergers
def conv(x):
    dict = {'two':2,
            'three':3,
            'five':5,
            'seven':7,
            'ten':10,
            'eleven':11,
            0:0 }
    return dict[x]

In [12]:
X['experience'] = X['experience'].apply(lambda x: conv(x))

In [13]:
X.head()

experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6

In [14]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   experience       8 non-null      int64  
 1   test_score       8 non-null      float64
 2   interview_score  8 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 320.0 bytes


In [15]:

Y = df.iloc[:,-1]
print(Y)

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64


In [16]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [17]:
lr.fit(X, Y)

LinearRegression()

In [18]:
y_pred = lr.predict(X)
y_pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [19]:
Y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [20]:
from sklearn.metrics import r2_score
r2_score(y_pred, Y)

0.9626511210293308

In [21]:
lr.predict([[3,9,7]])

array([58315.5019167])

In [22]:
lr.predict([[10,10,10]])

array([86612.80419155])

In [23]:
lr.predict([[10,2,3]])

array([55930.47274854])

**Model Deployment**

In [24]:
import pickle

pickle.dump(lr,open('Salaryprediction.pkl','wb'))

In [26]:
model = pickle.load(open('Salaryprediction.pkl','rb'))

In [27]:
model.predict([[3,9,7]])

array([58315.5019167])

In [28]:
model.predict([[10,10,10]])

array([86612.80419155])

In [29]:
model.predict([[10,2,3]])

array([55930.47274854])